
[options]
  bootstrap_after  = "s:cargo_task"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "autocomplete"
  enable = true 
[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rust-analyzer"]
